### PR TITLE
Package maintenance fixes

### PR DESCRIPTION
**Pull request by zimbatm**
Minor fixes to make it compatible with vagrant 0.8.x serie

### CODE REVIEW

**Comment by ambethia** [comment]
<3 Should merge this one :)

**Comment by mikkin** [comment]
Yes, this should be merged.

**Comment by dkubb** [comment]
@mitchellh Would it be possible to have the dependencies bumped on this gem to work with vagrant 1.0+ ?

**Comment by zimbatm** [comment]
Closing as it's probably not compatible with the newest versions of vagrant and I'm not using this anymore.

**Pull request closed without merging**
